#!/usr/bin/env bash
# set up a load balencer to responde to user
#sudo apt update
#sudo apt install haproxy
server_config=\
"

frontend http-in
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server server1 100.25.19.239:80 check
	server server2 52.91.153.239:80 check
"
echo "$server_config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
