#!/usr/bin/env bash
# set up a load balencer to responde to user
server_config=\
"

frontend http-in
	bind *:80
	mode http
	default_backend servers

backend servers
	balance roundrobin
	server server1 100.25.19.239:80 check
	server server2 52.91.153.239:80 check
"
apt -y update
apt -y install haproxy
echo "$server_config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
