#!/usr/bin/env bash
# script that print passwd content

while read -r line;do
	name=$(echo "$line" | cut -d ':' -f 1)
	id=$(echo "$line" | cut -d ':' -f 3)
	home=$(echo "$line" | cut -d ':' -f 6)
	echo "$name:$id:$home"
done < /etc/passwd
